guacamole-noauthlogged-build:
 build: ./
 volumes:
  - ./war:/usr/local/tomcat/webapps/
  - ./guac_home:/etc/guacamole
  - ./target:/etc/guacamole/extensions
  - ./:/opt/build
 ports:
  - 8080:8080
 environment:
  - GUACAMOLE_HOME=/etc/guacamole
 net: "host"
